######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 15 15:17:33 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtest.cpp
